version: 2.1
jobs:
  build:
    docker:
      - image: circleci/goland:1.15
        auth:
          username: dorison
          password: $DOCKERHUB_PASSWORD
  steps:
    - checkout

    - setup_remote_docker:
        version: 19.03.13
    
    - run: | 
        TAG=0.1.$CIRCLE_BUILD_NUM
        docker build -t dorison/test:$TAG .
        docker login -u dorison -p $DOCKERHUB_PASSWORD
        docker push dorison/test:$TAG
